#调度器配置

# 格式
#[group_name]
## 组描述, 可选, 默认 无
#desc='组描述'
## 进程数, 可选, 默认1
#spider_name.process = 1
## 提交初始化种子的时机, 可选, 默认 none
#spider_name.seed = '0 */3 * * *' # 这里表示每隔3小时提交一次初始化种子
## spider描述, 可选, 默认 无
#spider_name.desc = 'spdier描述'

# 示例
#[g1]
#spider1.process=1
#spider1.seed='0 * * * *'
#spider2.process=2
#spider2.seed='0 * * * *'
#[g2]
#spider1.process=1
#spider1.seed='0 * * * *'
