#调度器配置

# 格式
# # 组名.爬虫名
# [group_name.spider_name]
# # 进程数, 0表示禁用
# process = 1
# # 提交初始化种子的时机, 可选, 默认 none
# seed = '0 */3 * * *' # 这里表示每隔3小时提交一次初始化种子
# # spider描述, 可选, 默认 无
# desc = 'spdier描述'

# 示例
# [g1.spider1]
# process=1
# seed='0 * * * *'
# [g1.spider2]
# process=2
# seed='0 * * * *'

# [g2.spider1]
# process=1
# seed='0 * * * *'
