# 格式
#<组名>:
   #<爬虫名1>='<进程数>,<提交初始化种子的时机>'
   #<爬虫名2>='<进程数>,'
   #<爬虫名3>='<进程数>'
#<组名2>:
   #<爬虫名3>='<进程数>,<提交初始化种子的时机>'

#说明
#组名不能重复,爬虫名不能重复
#进程数小于1表示禁用, 进程数最大为99
#提交初始化种子的时机可以是一个cron表达式, 也可以是一个固定时间如 YYYY-MM-DD hh:mm:ss, 空表示不会提交初始化种子

# 示例
#g1:
   #spider1'1,0 */3 * * *'
   #spider2'0,2020-08-08 12:00:00'
   #spider3'0,'
   #spider4'0'
#g2:
   #spider3='1,'
